import { Track } from "./TypesNConsts";

export const tracksDummies: Track[] = [
	{
		title: "JavaScript",
		id: 13464575674545,
		complete: false,
		topics: [
			{
				title: "Arrays",
				id: 1346457567234534,
				complete: false,
				tasks: [
					{
						id: 2,
						name: "Read about arrays",
						deadline: new Date("2022/08/15"),
						topic: "Arrays",
						priority: true,
						completed: false,
					},
					{
						id: 4,
						name: "Use arrays 10 times",
						deadline: new Date("2022/08/15"),
						topic: "Arrays",
						priority: true,
						completed: false,
					},
					{
						id: 5,
						name: "Finish CodeCademy chapter on arrays",
						deadline: new Date("2022/08/15"),
						topic: "Arrays",
						priority: false,
						completed: false,
					},
					{
						id: 6,
						name: "Write blog post about arrays",
						deadline: new Date("2022/08/16"),
						topic: "Arrays",
						priority: false,
						completed: false,
					},
					{
						id: 7,
						name: "Design tattoo with array",
						deadline: new Date("2022/08/17"),
						topic: "Arrays",
						priority: false,
						completed: false,
					},
				],
			},
			{
				title: "Objects",
				id: 23535645,
				complete: false,
				tasks: [
					{
						id: 8,
						name: "Read about objects",
						deadline: new Date("2022/09/17"),
						topic: "Objects",
						priority: false,
						completed: false,
					},
					{
						id: 9,
						name: "Use objects 10 times",
						deadline: new Date("2022/09/17"),
						topic: "Objects",
						priority: false,
						completed: false,
					},
					{
						id: 10,
						name: "Finish CodeCademy chapter on objects",
						deadline: new Date("2022/08/11"),
						topic: "Objects",
						priority: false,
						completed: false,
					},
					{
						id: 11,
						name: "Write blog post about objects",
						deadline: new Date("2022/09/17"),
						topic: "Objects",
						priority: false,
						completed: false,
					},
					{
						id: 12,
						name: "Design tattoo with object",
						deadline: new Date("2022/09/17"),
						topic: "Objects",
						priority: false,
						completed: false,
					},
				],
			},
			{
				title: "Classes",
				id: 235,
				complete: false,
				tasks: [
					{
						id: 13,
						name: "Read about classes",
						deadline: new Date("2022/10/17"),
						topic: "Classes",
						priority: false,
						completed: false,
					},
					{
						id: 14,
						name: "Use classes 10 times",
						deadline: new Date("2022/10/17"),
						topic: "Classes",
						priority: false,
						completed: false,
					},
					{
						id: 15,
						name: "Finish CodeCademy chapter on classes",
						deadline: new Date("2022/10/17"),
						topic: "Classes",
						priority: false,
						completed: false,
					},
					{
						id: 16,
						name: "Write blog post about classes",
						deadline: new Date("2022/10/17"),
						topic: "Classes",
						priority: false,
						completed: false,
					},
					{
						id: 17,
						name: "Design tattoo with class",
						deadline: new Date("2022/10/17"),
						topic: "Classes",
						priority: false,
						completed: false,
					},
					{
						id: 18,
						name: "Read about loops",
						deadline: new Date("2022/11/17"),
						topic: "Classes",
						priority: false,
						completed: false,
					},
					{
						id: 19,
						name: "Use loops 10 times",
						deadline: new Date("2022/11/17"),
						topic: "Classes",
						priority: false,
						completed: false,
					},
					{
						id: 20,
						name: "Finish CodeCademy chapter on loops",
						deadline: new Date("2022/11/17"),
						topic: "Classes",
						priority: false,
						completed: false,
					},
					{
						id: 21,
						name: "Write blog post about loops",
						deadline: new Date("2022/11/17"),
						topic: "Classes",
						priority: false,
						completed: false,
					},
					{
						id: 22,
						name: "Design tattoo with loops",
						deadline: new Date("2022/11/17"),
						topic: "Classes",
						priority: false,
						completed: false,
					},
					{
						id: 23,
						name: "Read about if statements",
						deadline: new Date("2022/12/17"),
						topic: "Classes",
						priority: false,
						completed: false,
					},
					{
						id: 24,
						name: "Use if statements 10 times",
						deadline: new Date("2022/12/17"),
						topic: "Classes",
						priority: false,
						completed: false,
					},
					{
						id: 25,
						name: "Finish CodeCademy chapter on if statements",
						deadline: new Date("2022/12/17"),
						topic: "Classes",
						priority: false,
						completed: false,
					},
					{
						id: 26,
						name: "Write blog post about if statements",
						deadline: new Date("2022/12/17"),
						topic: "Classes",
						priority: false,
						completed: false,
					},
					{
						id: 27,
						name: "Design tattoo with if statements",
						deadline: new Date("2022/12/17"),
						topic: "Classes",
						priority: false,
						completed: false,
					},
				],
			},
		],
	},
	// {
	// 	title: "Guitar",
	// 	id: 13464575674545,
	// 	complete: false,
	// 	topics: [{}],
	// },

	// "Cooking",
	// "Tap Dance",
	// "React",
	// "Japanese",
];
